Blindbox, block trade tutorial, dual quota hint
Loopring/loopring-web-v2 pull request #732
Opened 2023-06-29 11:46 UTC by johnloopring

2023-06-29 12:39 UTC, windatang requested changes

2023-06-29 12:39 UTC, windatang commented on packages/component-lib/src/components/tableList/redPacketTable/RedPacketBlindBoxReceiveTable.tsx
> +        key: "Reveal Time",
key 最好不要加空格吧

2023-06-29 12:39 UTC, windatang commented on packages/component-lib/src/components/tableList/redPacketTable/RedPacketBlindBoxReceiveTable.tsx
> +        key: "Expired Time",
同上

2023-06-29 12:39 UTC, windatang commented on packages/component-lib/src/components/tableList/redPacketTable/RedPacketClaimTable.tsx
> +          ? "https://static.loopring.io/assets/images/blindbox_dark.png"
https://static.loopring.io/assets/  用 SoursURL

2023-06-29 12:39 UTC, windatang commented on packages/component-lib/src/components/tableList/redPacketTable/RedPacketClaimTable.tsx
> +          : "https://static.loopring.io/assets/images/blindbox_light.png",
同上

2023-06-29 12:39 UTC, windatang commented on packages/component-lib/src/components/text-tooltip/index.tsx
follow 现在的 textTooltip 做文件名称吧

2023-06-29 12:39 UTC, windatang commented on packages/webapp/src/pages/RedPacketPage/RedPacketMarketPanel/hooks.ts
> +                    modes: "0,1,2",
有时间最好写 enum 定义type, 和scope 一样
scopes: sdk.LuckyTokenViewType.PUBLIC,

2023-06-30 03:11 UTC, johnloopring commented on packages/component-lib/src/components/block/RedPacket.tsx
> +                                  {info.showMultiplier && "x"} {info.amount}
view，不是变量

2023-06-30 03:54 UTC, windatang approved these changes

2023-07-07 09:46 UTC, merged